---
- name: Install common system utilities for {{ ansible_os_family }}
  package:
    name: '{{ item[ansible_os_family|lower] | default(item["default"]) }}'
    state: 'present'
  with_items:
    - default: stow
    - default: direnv
    - default: socat
    - default: coreutils
    - default: automake
    - default: autoconf
    - default: htop
      darwin: htop-osx
