---
- name: Install emacs
  community.general.homebrew_cask:
    name: railwaycat/emacsmacport/emacs-mac
    state: latest
  when: ansible_os_family|lower == 'darwin'

- name: Install editor fonts
  community.general.homebrew_cask:
    name:
      - homebrew/cask-fonts/font-fira-mono-nerd-font
    state: latest
  when: ansible_os_family|lower == 'darwin'

- name: Install doom emacs
  ansible.builtin.git:
    repo: "https://github.com/hlissner/doom-emacs"
    dest: "${HOME}/.emacs.d"
    depth: 1

- name: Install Visual Studio Code
  community.general.homebrew_cask:
    name: visual-studio-code
    state: latest
