---
os: osx
osx_image: xcode9.4
language: objective-c

install:
  - sudo easy_install pip
  - sudo pip install ansible

script:
  # Check syntax
  - ansible-playbook --syntax-check playbook.yml

  # Execute playbook (with 20 minute extension)
  - travis_wait ansible-playbook playbook.yml
