os: osx
osx_image: xcode11
language: objective-c
addons:
  homebrew:
    update: true
install:
  - sudo easy_install pip
  - sudo pip install --upgrade pip
  - sudo pip install jmespath
  - sudo pip install ansible
script:
  - ansible-playbook --syntax-check playbook.yml
  - ansible-playbook playbook.yml
