---
- name: Provision Workspace
  hosts: localhost
  connection: local

  vars:
    use_dotfiles: true

  roles:
    - role: system-utils
    - role: editors
      tags: [editors]
    - role: development
    - role: misc
    - role: zsh
      tags: [zsh, shell]
    - role: go-dev
      tags: [go, golang, development]
    - role: node-dev
      tags: [node, development]
    - role: python-dev
      tags: [python, development]
    - role: alfred
      tags: [productivity, macos]
