---
- name: Provision Workspace
  hosts: localhost
  connection: local

  roles:
    - role: system-utils
      tags: [system]
    - role: editors
      tags: [editors, development]
    - role: development
      tags: [development]
    - role: misc
      tags: [misc, macos]
    - role: zsh
      tags: [zsh, shell]
    - role: go-dev
      tags: [go, golang, development]
    - role: node-dev
      tags: [node, development]
    - role: python-dev
      tags: [python, development]
    - role: shell-utils
      tags: [shell, shell-utils, development]
    - role: desktop
      tags: [desktop, macos]
    - role: version-control
      tags: [vcs]
    - role: file
      tags: [file, development]
    - role: entertainment
      tags: [entertainment, macos]
    - role: web
      tags: [web, macos]
    - role: productivity
      tags: [productivity, macos]
    - role: hardware
      tags: [hardware, drivers, macos]
