---
- name: Provision Workspace
  hosts: localhost
  connection: local

  vars:
    use_dotfiles: true

  roles:
    - role: system-utils
      tags: [system]
    - role: editors
      tags: [editors, development]
    - role: development
    - role: misc
      tags: [misc, macos]
    - role: zsh
      tags: [zsh, shell]
    - role: go-dev
      tags: [go, golang, development]
    - role: node-dev
      tags: [node, development]
    - role: python-dev
      tags: [python, development]
    - role: shell-utils
      tags: [shell, shell-utils, development]
    - role: alfred
      tags: [productivity, macos]
    - role: desktop
      tags: [desktop, macos]
