---
- name: Clone dotfiles repository
  git:
    repo: git@github.com:MinnSoe/dotfiles.git
    dest: ~/dotfiles
    force: yes
    accept_hostkey: yes
  when: use_dotfiles
  become: no

- name: Symlink {{ app }}
  shell: stow -d {{ dotfiles_path }} -t ~/ {{ app }}
  when: use_dotfiles
