---
- name: Clone dotfiles repository
  git:
    repo: 'https://github.com/MinnSoe/dotfiles.git'
    dest: ~/dotfiles
    force: yes
  when: zsh_should_use_dotfiles == True

- name: Symlink {{ app }}
  shell: stow -d {{ dotfiles_path }} -t ~/ {{ app }}
  when: zsh_should_use_dotfiles == True
