---
- name: Clone dotfiles repository
  git:
    repo: 'https://github.com/MinnSoe/dotfiles.git'
    dest: ~/dotfiles
    force: no
    update: no
  when: use_dotfiles
  become: no

- name: Symlink {{ app }}
  shell: stow -d {{ dotfiles_path }} -t ~/ {{ app }}
  when: use_dotfiles
