---
- name: Link user provided zsh configuration
  include_role:
    name: dotfiles
  vars:
    app: zsh

- name: Create .zshrc file if it does not exist
  copy:
    content: ''
    force: false
    dest: '{{ ansible_env.HOME }}/.zshrc'
    owner: '{{ zsh_user }}'
    mode: 0644
