---
- name: Ensure zsh and dependencies are present
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - zsh
    - git
    - stow

- name: Set zsh path to system zsh
  command: which zsh
  register: zsh_path

- name: Set zsh path to homebrew zsh
  set_fact: zsh_path={{ zsh_homebrew_path }}
  when: ansible_os_family|lower == 'darwin'

- name: Ensure zsh ({{ zsh_path }}) is in allowed shells (/etc/shells)
  lineinfile:
    path: '/etc/shells'
    line: '{{ zsh_path }}'
  become: true

- name: Set zsh as default shell for {{ zsh_user }}
  user:
    name: '{{ zsh_user }}'
    shell: '{{ zsh_path }}'
  become: true

- name: Clone antigen into .zsh
  git: repo=https://github.com/zsh-users/antigen.git dest={{ zsh_antigen_path }}
