---
- name: Ensure shell packages are installed
  package:
    name: '{{ item[ansible_os_family|lower] | default(item["default"]) }}'
    state: 'present'
  with_items:
    # fuzzy file finder
    - default: 'fzf'
    # terminal multiplexer
    - default: 'tmux'
    # cross-shell prompt
    - default: 'starship'

- name: Link dotfiles starship configuration
  include_role:
    name: dotfiles
  vars:
    app: starship
