---
- name: Ensure shell packages are installed
  package:
    name: '{{ item[ansible_os_family|lower] | default(item["default"]) }}'
    state: 'present'
  with_items:
    # fuzzy file finder
    - default: 'fzf'
    # terminal multiplexer
    - default: 'tmux'
    # cross-shell prompt
    - default: 'starship'
    # cat clone with syntax highlighting and Git integration
    - default: 'bat'
    # zsh antigen plugin manager alternative
    - default: 'antibody'
    # simple, fast and user-friendly alternative to find
    - default: 'fd'
      debian: 'fd-find'

- name: Link dotfiles starship configuration
  include_role:
    name: dotfiles
  vars:
    app: starship

- name: Install tmux plugin manager
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: '~/.tmux/plugins/tpm'

- name: Link dotfiles tmux configuration
  include_role:
    name: dotfiles
  vars:
    app: tmux
