---
- name: Ensure go installed
  package:
    name: golang # matches name in debian as well as homebrew alias
    state: present

- name: Ensure default go workspace directory is present
  file:
    path: ~/go
    state: directory
    mode: '0755'

- name: Install development go packages
  shell: 'GO111MODULE=on go get -u {{ item }}'
  with_items:
    - golang.org/x/tools/cmd/godoc
    - golang.org/x/lint/golint
    - golang.org/x/tools/cmd/goimports
    - golang.org/x/tools/cmd/gorename
    - golang.org/x/tools/cmd/guru
    - github.com/cweill/gotests/...
    - github.com/davidrjenni/reftools/cmd/fillstruct
    - github.com/fatih/gomodifytags
    - github.com/godoctor/godoctor
    - github.com/haya14busa/gopkgs/cmd/gopkgs
    - github.com/josharian/impl
    - github.com/mdempsky/gocode
    - github.com/rogpeppe/godef
    - github.com/zmb3/gogetdoc

- name: Install latest gopls
  shell: >-
    GO111MODULE=on go get golang.org/x/tools/gopls@latest

- name: Install golangci-lint
  shell: >-
    GO111MODULE=on \
    CGO_ENABLED=0 \
    go get -v -trimpath -ldflags '-s -w' \
    github.com/golangci/golangci-lint/cmd/golangci-lint
